cspm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns = urlpatterns + [url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})]

home/urls.py
from django.urls import path
from . import views
from django.shortcuts import redirect

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('query/', views.query, name='query'),
    path('covid_experience/', views.covid_experience, name='covid_experience'),
    path('read_experience/', views.read_experience, name='read_experience'),
    path('symptoms_wordcloud/', views.symptoms_wordcloud, name='symptoms_wordcloud'),
    path('population_chart/', views.population_chart, name='population_chart'),
]

home/models.py
from django.db import models

GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('None', 'None'),
    ('Other', 'Other'),
)


TIME_CHOICES = (
    ('1st Wave', '1st Wave'),
    ('2nd Wave', '2nd Wave'),
    ('Both', 'Both'),
)


SOURCE_CHOICES = (
    ('Quora', 'Quora'),
    ('Reddit', 'Reddit'),
    ('Survey', 'Survey'),
)


class Queries(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False, verbose_name='Name')
    email = models.EmailField(blank=False, null=False, verbose_name='Email')
    subject = models.CharField(max_length=200, blank=False, null=False, verbose_name='Subject')
    message = models.CharField(max_length=2000, blank=False, null=False, verbose_name='Message')

    def __str__(self):
        return self.subject

class CovidExperience(models.Model):
    email = models.EmailField(blank=True, null=True, verbose_name='Email')
    name = models.CharField(max_length=40, blank=True, null=True, verbose_name='Name')
    age = models.IntegerField(blank=True, null=True, verbose_name='Age')
    mobile = models.CharField(max_length=10, blank=True, null=True, verbose_name='Contact')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, verbose_name='Gender', default='None')
    source = models.CharField(max_length=20, choices=SOURCE_CHOICES, verbose_name='Source', default='Survey')
    time_of_infection = models.CharField(max_length=10, choices=TIME_CHOICES, verbose_name='The time of Infection', default='1st Wave')
    testing_date1 = models.DateField(verbose_name="Testing Date (positive result date only)", null=True, blank=True)
    testing_date2 = models.DateField(verbose_name="Testing Date(optional)", null=True, blank=True)
    experience = models.CharField(max_length=5000, blank=False, null=False, verbose_name='Experience')
    islongcovid = models.BooleanField(verbose_name='Is Long Covid', default=False, blank=True, null=True)

    def __str__(self):
        return str(self.pk)


class QueryReply(models.Model):
    experience = models.ForeignKey(CovidExperience, on_delete=models.CASCADE, related_name='experience_obj')
    text = models.CharField(max_length=1000, blank=False, null=False, verbose_name='Reply')
    def __str__(self):
        return str(self.pk)


class Symptom(models.Model):
    name = models.CharField(max_length=40, blank=False, null=False, verbose_name='Name')
    count = models.IntegerField(blank=False, null=False)

    def __str__(self):
        return str(self.name)

home/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Queries, CovidExperience, QueryReply, Symptom

def home(request):
    total_experiences = len(CovidExperience.objects.all())
    normal_covid_experiences = len(CovidExperience.objects.filter(islongcovid=False))
    long_covid_experiences = len(CovidExperience.objects.filter(islongcovid=True))

    quora_covid_experiences = len(CovidExperience.objects.filter(source="Quora"))
    reddit_covid_experiences = len(CovidExperience.objects.filter(source="Reddit"))
    survey_covid_experiences = len(CovidExperience.objects.filter(source="Survey"))

    return render(request, 'home.html', {'total_experiences': total_experiences, 'normal_covid_experiences': normal_covid_experiences, 'long_covid_experiences': long_covid_experiences, 'quora_covid_experiences': quora_covid_experiences, 'reddit_covid_experiences': reddit_covid_experiences, 'survey_covid_experiences': survey_covid_experiences})


def query(request):
    if(request.method == "POST"):
        data = request.POST
        name = data['name']
        email = data['email']
        subject = data['subject']
        message = data['message']

        query = Queries.objects.create(name=name, email=email, subject=subject, message=message)
        query.save()

    return redirect('/')


def covid_experience(request):
    if(request.method == "POST"):
        data = request.POST
        name = data['name']
        email = data['email']
        age = data['age']
        mobile = data['mobile']
        gender = data['gender']
        time_of_infection = data['time_of_infection']
        testing_date1 = data['testing_date1']
        testing_date2 = data['testing_date2']
        experience = data['experience']

        covid_experience = CovidExperience.objects.create(experience=experience)
        covid_experience.save()

    return render(request, 'form.html')


def read_experience(request):
    experiences = CovidExperience.objects.all()
    replies = QueryReply.objects.all()
    
    return render(request, 'experiences.html', {'experiences': experiences, 'replies': replies})


def symptoms_wordcloud(request):
    return render(request, 'wordcloud.html')


def population_chart(request):
    labels = []
    data = []
    symptoms = Symptom.objects.all()
    for obj in symptoms:
        labels.append(obj.name)
        data.append(obj.count)

    return JsonResponse(data={
        'labels': labels,
        'data': data,
    })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/cspm_logo.jpg' %}" rel="icon">
  <link href="{% static 'img/cspm_logo.jpg' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  {% block head_links %} {% endblock %}

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  {% block style %} {% endblock %}
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
      <div class="align-items-center d-none d-md-flex">
        <i class="bi bi-clock"></i> Participatory Medicine Survey
      </div>
      <div class="d-flex align-items-center">
        <i class="bi bi-phone"></i> Email us on info.cspm.iitj@gmail.com for any details
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <a href="/" class="logo me-auto"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt1YhKakUYqrSFQ2uLwYkIpM37gwyP0u0x2Q&usqp=CAU" alt=""></a>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <h1 class="logo me-auto"><a href="index.html">Medicio</a></h1> -->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto " href="/">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home:symptoms_wordcloud' %}">Symptoms</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home:covid_experience' %}">Custom Form</a></li>
          <li><a class="nav-link scrollto" href="#contact">Contact Us</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home:read_experience' %}">Read Experiences</a></li>
          <li><a class="nav-link scrollto" href="#">Benefits of doing survey</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="https://docs.google.com/forms/d/e/1FAIpQLSd6NmU9tIN8Xjg3VSs7TGoHKYVeXW-YolgJJjXtwoAjlIInuw/viewform" class="appointment-btn scrollto"><span class="d-none d-md-inline">Take</span> Participatory Medicine Survey</a>

    </div>
  </header><!-- End Header -->
  
  {% if messages %}
  {% for message in messages %}
  <div id="alert"
    style="position: absolute; top: 10%; width: 70%; left: 50%; transform: translateX(-50%); opacity: 1; z-index: 10;"
    class="alert alert-info alert-dismissible" role="alert">
    {{message}}
    <p style="color: #055160; position: absolute; right: 15px; top: 50%; transform: translateY(-50%); font-size: 1rem; cursor: pointer;"
      onclick="document.getElementById('alert').style.display = 'none'"><i class="fas fa-times"></i></p>
  </div>
  {% endfor %}
  {% endif %}

  {% block content %}

  {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6">
            <div class="footer-info">
              <h3>Crowdsource Participatory Medicine Framework</h3>
              <p>
                <strong>Phone:</strong> +91 9358178089<br>
                <strong>Email:</strong> info.cspm.iitj@gmail.com<br>
              </p>
              <div class="social-links mt-3">
                <a href="" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
              </div>
            </div>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Participatory Medicine</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms & Condition</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Redirect</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Team</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Contact Us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">IIT Jodhpur</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">COVID 19</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="https://docs.google.com/forms/d/e/1FAIpQLSd6NmU9tIN8Xjg3VSs7TGoHKYVeXW-YolgJJjXtwoAjlIInuw/viewform">Survey</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Hear from us</h4>
            <p>Type your email ida</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Crowdsource Participation Medicine Framework</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
        All the links in the footer should remain intact.
         You can delete the links only if you purchased the pro version. 
        Licensing information: https://bootstrapmade.com/license/ 
        Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medicio-free-bootstrap-theme/ 
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer>End Footer
-->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  {% block js %}

  {% endblock %}

</body>

</html>

templates/experiences.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Covid Experiences
{% endblock %}

{% block head_links %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/dcc97d25c8.js" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,500' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/cant89/gianni-accordion-js/dist/gianniAccordion.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
    <link href="{% static 'css/table.css' %}" rel="stylesheet">
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<section id="contact" class="contact" style="margin-top: 70px;">
    <div class="type-yoga-container p-4">
        <div class= "container">
            <div class="row">
                <div class="col-12">
                    <div class="text-center">
                        <h1 class="type-of-yoga-heading">Covid Experiences</h1>
                    </div>
    {% for e in experiences %}
        <div class="card-container mb-3">
            <div class="d-flex flex-row">
                <div class="d-flex flex-column justify-content-center p-3">
                    <div>
                        <h1 class="type-yoga-heading">Experience ID: {{e.pk}}</h1>
                        <p class="type-yoga-para">{{e.experience}}</p>
                    </div>
                </div>
            </div>
        <div>
        <section class="card" style="margin-bottom: 30px;">
            {% for r in replies %}
                {% if r.experience == e %}
                    <article>
                        <h1 data-accordion-element-trigger class="h1-acordian">Reply ID {{ r.id }}</h1>
                        <div data-accordion-element-content class="content">
                            <p class="p-acordian">{{r.text}}</p>
                        </div>
                    </article>
                {% endif %}
            {% endfor %}
        </section>
    {% endfor %}
</div>
</section><!-- End Contact Section -->
{% endblock %}
{% block js %}
<script src="{% static 'js/table.js' %}"></script>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Data Collection Form
{% endblock %}

{% block head_links %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<section id="contact" class="contact">
    <div id="contact_form" class="container">

      <div class="section-title">
        <h2>Crowdsourced Participatory Medicine Questionnaire
        </h2>
      </div>

    </div>

    <div><!--
      <iframe style="border:0; width: 100%; height: 350px;" src="" frameborder="0" allowfullscreen></iframe> -->
    </div>

    <div class="container">
        <div class="col-lg-12">
            <form action="/covid_experience/" method="POST"  role="form" class="php-email-form">
                {% csrf_token %}
                <p style="margin-bottom: 0px; color:red">Info of the person filling the form</p>
                <div class="row" style="align-items: end;">
                    <div class="form-group col-md-4" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="example@gmail.com">
                    </div>
                    <div class="form-group col-md-4" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Name</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name">
                    </div>
                    <div class="form-group col-md-4" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Mobile Number</label>
                        <input type="text" id="mobile" class="form-control" name="mobile">
                    </div>
                </div>
                <p style="margin-top: 20px; margin-bottom: 0px; color:red">Info of the patient</p>
                <div class="row" style="align-items: end;">
                    <div class="form-group col-md-6" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Age</label>
                        <input type="number" class="form-control" name="age" id="age" placeholder="Your Age">
                    </div>
                    <div class="form-group col-md-6" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Gender <span style="color: red;">*</span></label>
                        <select class="form-control" name="gender" id="gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Other</option>
                        </select>
                    </div>
                </div>
                <div class="row" style="align-items: end;">
                    <div class="form-group col-md-4" style="margin-top: 10px; margin-bottom: 10px">
                        <label>The time of Infection <span style="color: red;">*</span></label>
                        <select class="form-control" name="time_of_infection" id="time_of_infection">
                            <option>1st Wave</option>
                            <option>2nd Wave</option>
                            <option>Both</option>
                        </select>
                    </div>
                    <div class="form-group col-md-4" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Testing Date (for 1st wave)</label>
                        <!-- <small id="testdatehelp" class="form-text text-muted">(specify positive result date only)</small> -->
                        <input type="date" id="test_date" class="form-control" name="testing_date1">
                        
                    </div>
                    <div class="form-group col-md-4" style="margin-top: 10px; margin-bottom: 10px">
                        <label>Testing Date (for 2nd wave)</label>
                        <input type="date" id="test_date" class="form-control" name="testing_date2">
                    </div>
                </div>
                <div class="form-group mt-3">
                    <label>Write experience here (max size: 5000 characters)<span style="color: red;">*</span> </label>
                    <textarea class="form-control" rows="5" name="experience" placeholder="" required></textarea>
                </div>
                <div class="my-3">
                    
                </div>
              <div class="text-center"><button class="appointment-btn" type="submit">Submit</button></div>
            </form>
          </div>
    </div>
  </section><!-- End Contact Section -->
{% endblock %}

templates/wordcloud.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Word Cloud
{% endblock %}

{% block head_links %}
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<section id="cta" class="cta" style="margin-top: 80px; background: white;">
    <div class="container" data-aos="zoom-in">
      <div class="text-center">
        <h3 style="margin-top: 25px;margin-bottom:15px; color:black">Symptom's Bar Chart</h3>
        <!-- <canvas id="myChart" style="width:100%;max-width:700px; display:inline; background: #9cf1f1; padding: 13px;"></canvas> -->
        <canvas id="population-chart" data-url="{% url 'home:population_chart' %}" style="width:100%;max-width:900px; display:inline; padding: 13px;"></canvas>
      </div>

    </div>
    
</section>
{% endblock %}

{% block js %}
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script>

    $(function () {

      var $populationChart = $("#population-chart");
      $.ajax({
        url: $populationChart.data("url"),
        success: function (data) {

          var ctx = $populationChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Symptom',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: ''
              }
            }
          });

        }
      });

    });

  </script>
{% endblock %}